.TH AN_FD_CLR 3 2005-01-03 "Antinat" "Antinat Programmer's Manual"
.SH NAME
.PP
AN_FD_CLR - remove an Antinat connection handle from a socket set.
.SH SYNOPSIS
.PP
.B #include <antinat.h>
.sp
.BI "void AN_FD_CLR(ANCONN " s ", struct fd_set * " fds " );"
.SH DESCRIPTION
.PP
The
.BR AN_FD_CLR (3)
function removes an Antinat socket from a set of file descriptors.  This
set of file descriptors can be used with
.BR select .
Use the
.BR AN_FD_ISSET (3)
function to determine if a file descriptor is in the set, or
.BR AN_FD_SET (3)
to place the file descriptor into the set.
This function should be considered equivalent to the FD_CLR macro in
your sockets library, except that it is for use with Antinat sockets.
.PP
.I s
is a socket previously created with
.BR an_new_connection (3).
.PP
.I fds
is an fd_set socket structure.  Consult your platform's documentation for
the
.BR select 
function for more information about this structure.  It will
contain a list of file descriptors suitable for use with the
.BR select 
call.
.SH RETURN VALUE
.PP
There is no return value.
.SH ERRORS
.PP
There is no error return.
.SH "SEE ALSO"
.PP
.BR select ,
.BR AN_FD_ISSET (3),
.BR AN_FD_SET (3),
.BR an_new_connection (3)
.SH AUTHOR
.PP
Malcolm Smith <malxau@users.sourceforge.net>
