.TH AN_UNSET_PROXY 3 2005-01-03 "Antinat" "Antinat Programmer's Manual"
.SH NAME
.PP
an_unset_proxy - set a proxy capable socket to not use a proxy
.SH SYNOPSIS
.PP
.B #include <antinat.h>
.sp
.BI "int an_unset_proxy(ANCONN " s ");"
.SH DESCRIPTION
.PP
The
.BR an_unset_proxy (3)
function is used to remove any proxy server specification.  Given that the
default value for a newly created socket is derived from the
.I AN_PROXY
environment variable, this function should be used if you are certain
that a proxy should not be used on a socket.  If a proxy should be used
on the socket, call either the
.BR an_set_proxy (3)
or
.BR an_set_proxy_url (3)
function.
.PP
.I s
is a socket previously created with
.BR an_new_connection (3).
.SH RETURN VALUE
.PP
This call returns
.B AN_ERROR_SUCCESS
to indicate successful completion.
.SH ERRORS
.TP
.B AN_ERROR_INVALIDARG
The socket handle is invalid.
.SH "SEE ALSO"
.PP
.BR an_new_connection (3),
.BR an_set_proxy (3),
.BR an_set_proxy_url (3)
.SH AUTHOR
.PP
Malcolm Smith <malxau@users.sourceforge.net>
