.TH ANTINAT 1 "6 January 2005"
.SH NAME
.PP
antinat \- A SOCKS server
.SH DESCRIPTION
.PP
This program provides a powerful, configurable and flexible SOCKS server.
.SH OPTIONS
.TP
.BI "-a"
On Win32, this option forces antinat to run as a user application (rather
than as a service.)  This option is not supported on UNIX/Linux.
.TP
.BI "-c filename"
Specifies a path to antinat.xml.  Normally, this is not used and antinat will
look for antinat.xml in the path specified for configuration files when it
was compiled (or on Win32, in the current directory.)
.TP
.BI "-h"
Display a brief listing of options supported by your build of Antinat.
.TP
.BI "-i"
On Win32, this option installs the running copy of Antinat as a Win32
service.  The path and setup for antinat will be determined at runtime.
This option is not supported on UNIX/Linux.
.TP
.BI "-r"
On Win32, this option removes the running copy of Antinat from the Win32
service list.  This option is not supported on UNIX/Linux.
.TP
.BI "-x"
If specified, this switch forces antinat not to daemonize and to remain
attached to the console.  Note that this is the only behavior if compiled with
the --with-feedback configuration option.
.SH "SEE ALSO"
.PP
.BR antinat.xml (4)
.SH AUTHOR
.PP
Malcolm Smith <malxau@users.sourceforge.net>
